[package]
name = "lorenz-attractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.33.0"
nalgebra = "0.29"
palette = "0.2.1"
rand = "0.8.5"
